name: 'Build'
on:
  - 'push'
  - 'pull_request'
jobs:
  linux:
    name: "Linux"
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - 'Release'
          - 'Debug'
        image:
          - 'clang-11'
          - 'clang-14'
          - 'gcc-9'
          - 'gcc-12'
    runs-on: 'ubuntu-latest'
    container:
      image: 'ghcr.io/lmichaelis/images:${{matrix.image}}'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Configure'
        run: 'cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DZK_BUILD_EXAMPLES=ON -DZK_BUILD_TESTS=ON'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest --output-on-failure'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '24'
      - name: 'Install dependencies'
        run: 'npm install'
      - name: 'Build WASM'
        run: 'emcmake cmake -B build-wasm -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DZK_BUILD_WASM=ON && emcmake cmake --build build-wasm'
      - name: 'Run Jest tests'
        run: 'npm test'

  windows:
    name: "Windows"
    runs-on: 'windows-2019'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'
      - name: 'Configure'
        shell: 'bash'
        run: 'cmake -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DZK_BUILD_EXAMPLES=ON -DZK_BUILD_TESTS=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5'
      - name: 'Build'
        run: 'cmake --build build --config Release -j 2'
      - name: 'Test'
        working-directory: 'build/'
        run: 'ctest -C Release --output-on-failure'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '24'
      - name: 'Install dependencies'
        run: 'npm install'
      - name: 'Build WASM'
        run: 'emcmake cmake -B build-wasm -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DZK_BUILD_WASM=ON && emcmake cmake --build build-wasm'
      - name: 'Run Jest tests'
        run: 'npm test'
