name: Release

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  release-wasm:
    runs-on: ubuntu-latest
    container:
      image: 'emscripten/emsdk:4.0.13'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com

      - run: npm install
      - run: npm run build:wasm

      - name: Package and publish
        run: |
          cd build-wasm/wasm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
